### ISSUE TITLE
[web] Minor shading error

### ISSUE THREAD

**Issue by ejurgensen** [ejurgensen/forked-daapd#1003]
@chme I noticed that if you scroll down a bit, and then select the speaker menu, the shading only covers some of the screen. See below. Reproduces in Chrome and Firefox.

<img width="949" alt="shading_error" src="https://user-images.githubusercontent.com/1156686/81736060-4c0ac180-9496-11ea-8392-bc0f8d40779e.png">

**Comment by cdlenfert** [comment]
Is it also the intention for the black bar to go all the way to the top of the viewport when the speaker list is toggled on mobile? Maybe I'm wrong, and it's just that I have a long list of speakers.
![image](https://user-images.githubusercontent.com/17277745/81834955-e7378180-94fe-11ea-83a0-01212bb667d0.png)
I ask because toggling the library/settings panel occupies the entire screen.
![image](https://user-images.githubusercontent.com/17277745/81835350-6331c980-94ff-11ea-99c4-72c785bfaf0c.png)

**Comment by chme** [comment]
> Is it also the intention for the black bar to go all the way to the top of the viewport when the speaker list is toggled on mobile? 

Yes, it is intentional. Originally i had it cover the whole page, so the black bar would cover the top navbar, but that does not seem to work with Safari on iOS. So opening the speaker list covers only part of the screen to workaround this issue (https://github.com/ejurgensen/forked-daapd/issues/978#issuecomment-622318725)
