### ISSUE TITLE
iTunes library parsing error: Album split into two

### ISSUE THREAD

**Issue by minfrin** [ejurgensen/forked-daapd#1036]
After importing an iTunes library, some albums are being split into two.

They appear in the library twice, with some songs in the one "album" and other songs in the other, like this:

<img width="866" alt="adele-split-1" src="https://user-images.githubusercontent.com/1331788/84808560-1f077c80-b009-11ea-9f54-2e19a43b974c.png">

The second album looks like this:

<img width="857" alt="adele-split-2" src="https://user-images.githubusercontent.com/1331788/84808602-2fb7f280-b009-11ea-8f70-47ef8ca34edf.png">

The option itunes_overrides is true.

**Comment by ejurgensen** [comment]
This is probably because there is some metadata that indicates to forked-daapd that the tracks belong to different albums. Exactly what that metadata is requires a bit of digging, especially since with itunes_overrides it can come both from the itunes xml and from the files themselves. I suggest you run ffprobe on two of the tracks that are split, e.g. 2 and 3. Then also try to find the tracks in the xml. Then post the data here, and I should be able to say what it is that causes this.

**Comment by ejurgensen** [comment]
Closing, no feedback
