### ISSUE TITLE
HTTP Stream in web interface not working on iOS

### ISSUE THREAD

**Issue by cdlenfert** [ejurgensen/forked-daapd#1037]
I'm slow to join the party on this, so apologies if this is a known issue.

I've been trying to use the HTTP stream on my iPhone 8 running iOS 13.5. In both Chrome and Safari browsers (as well as the web app version via the home screen shortcut) and none of them will start the mp3 stream from within the FD web interface. It does work to visit the stream URL directly in these browsers, but it would be so much nicer to be able to start/stop playback directly from the web interface. It does work to do this on my Mac via Chrome and Safari, just not on iOS.

**Comment by chme** [comment]
This might be the issue: https://stackoverflow.com/questions/29373563/audiocontext-on-safari

Will take a look at fixing it ...

**Comment by cdlenfert** [comment]
updated: fixed typo in title (stream instead of steam). The steam coming off my RasPi is unrelated 😛

**Comment by chme** [comment]
Looks like this is a bug in iOS 13.5 that was fixed in iOS 13.6 (https://bugs.webkit.org/show_bug.cgi?id=211394).
(the audiocontext creation stuff from the stackoverflow article linked in my previous comment is already done in the web interface)

@cdlenfert If you have the possibility to check with iOS 13.6 and report back if it is working, that would be great.

**Comment by cdlenfert** [comment]
@chme Thanks for checking back in on this. I'd love to test this and confirm the 13.6 fix but I've got 2 barriers: I'm sticking on 13.5 for my device since I'm jailbroken, and I'm no longer running FD off a Raspberry Pi and my current device (PogoPlug E-02) doesn't have the resources to transcode an MP3 stream. If that changes I'll try to post back with some test results.

**Comment by ejurgensen** [comment]
Thanks for looking into this @chme. I have 13.7 and made a quick test, and it seems to work fine. So hope it is ok if I close this issue, otherwise let me know.

**Comment by dr-leo** [comment]
On a preliminary note, I am a huge fan of FD/Owntone since 2020, using it daily through IOS Remote on iPhone. 

A new usecase prompted me to test the access through the web interface on iPhone/Safari (IOS 18.2). Here, I ran into multiple issues. The HTTP stream function is not stable, and it looks like I'm [not alone](https://www.reddit.com/r/selfhosted/comments/z4ymu5/some_questions_about_owntone_formerly_forkeddaapd/). The library displays the history, but not the list of albums etc. On an iPad, likewise with IOS 18.2, the library looks better, but the HTTP stream problem seems to pop up as well.

**Comment by hacketiwack** [comment]
@dr-leo can you specify which version of OwnTone you are using?
Also, when you say "not stable", what do you mean by that?
And finally, do you have screenshots of the library not displaying the list of albums?
Thanks
