### ISSUE TITLE
Avoid transcoding unless necessary

### ISSUE THREAD

**Issue by mouth4war** [ejurgensen/forked-daapd#1046]
Feature request: Can there be a check before transcoding for if the source file meets the output requirements to avoid transcoding every file?

**Comment by ejurgensen** [comment]
Can you elaborate on which output use case you are referring to? I.e. is it Airplay or one of the others?

**Comment by mouth4war** [comment]
I meant Chromecast, which supports AAC, MP3 and FLAC AFAIK.

**Comment by ejurgensen** [comment]
forked-daapd uses RTP to send to a Chromecast, and in that mode I could only get Opus-encoding to work. Chromecasts also support serving a stream to them (so not RTP), and in that mode more formats are supported, like you say. Previous versions of forked-daapd used that, but starting playback was very slow, and it didn't seem like any control of playback timing would possible. So that's why RTP/Opus is currently used.
