### ISSUE TITLE
Sound stream via the website (http://forked-daapd:3689/) or iOS Remote doesn't working

### ISSUE THREAD

**Issue by petrvirus** [ejurgensen/forked-daapd#1059]
Hi all,

Help me to solve my issue:
I installed forded-daapd 27.1 at freebsd. And successfuly connetcting my macos (Music app) and iOS (Remote app). At macos all working perfectly.

But when I try to listen to music through iOS (Remote app), I can't hear the sound from my iPhone (including headphones). 
Also, I noticed that an attempt to listen music at my iPhone (Remote app) starts its playback in the web interface player (http://forked-daapd:3689/). However, this does not play the sound anywhere. 
I also noticed that attempts to play music via a web player (http://forked-daapd:3689/) are displayed it in all Remote app (with the same song). 
I would like to configure the server daapd so that each iOS client connected to the Forked-daapd iTunes server can play music through their headphones or speakerfone.
Can you please tell me is it possible?

Best regards,
Petr

**Comment by ejurgensen** [comment]
iOS Remote and the web UI are remote controls, not media players like iTunes/Apple Music. So you use them to control where the music is played, which is normally Airplay speakers, or on the device itself (your FreeBSD device).

It sounds like you are looking for either a DAAP client for your iPhone (an app that can play music served by forked-daapd or iTunes), or having an app that makes your iPhone act as an Airplay speaker. I don't think such apps exist, which may be due to Apple app store policies.

That said, there is one way of listening on iPhone, but I'm not sure how well it works in practice. See issue #1037 and http://ejurgensen.github.io/forked-daapd/#mp3-network-streaming-streaming-to-ios

**Comment by LordMyschkin** [comment]
May I say that - beside the lag from buffering - music through MP3 streaming on the iPhone works pretty well! I use „vlc media player" as client, wich works better than playing in a browser.
