### ISSUE TITLE
Audio drop outs

### ISSUE THREAD

**Issue by boblund** [ejurgensen/forked-daapd#1062]
On a raspberry pi3 with hifiberry dac+ pro I get several second random audio drop outs and the following log entry:

[2020-07-21 06:46:07] [  LOG]   laudio: open '/dev/snd/pcmC1D0p' failed (-16)[2020-07-21 06:46:07] [  LOG]   laudio: ALSA device 'hw:1' won't open due to existing session (no support for concurrent audio), truncating audio

Sometimes this happens every few minutes and sometimes there is up to 60 minutes between occurrences. AKAIK no other app would be trying to write to the device. I have tried the dac as the default and on hw:0 (local dac disabled) and hw:1 (local dac enabled) and get similar behavior.

Any help on solutions or paths to troubleshoot are welcome.

**Comment by boblund** [comment]
I should add that I am running a full raspbian stretch and the music is coming off a USB disk.

**Comment by whatdoineed2do** [comment]
This is because the hifiberry DAC can't have multiple open (the pcm512x chip used in the IQaudioDAC and AlloBoss DAC - it also happens on a USB DAC) which is what the server does.

See for potential workaround that you need to create an ALSA `dmix` device:
https://github.com/ejurgensen/forked-daapd/blob/master/README_ALSA.md#handling-devices-that-cannot-concurrently-play-multiple-audio-streams

**Comment by boblund** [comment]
Thanks for the pointer.
