### ISSUE TITLE
Can't stream to various new Chromecast devices e.g. Xiaomi Mi and Nvidia Shield

### ISSUE THREAD

**Issue by keizie** [ejurgensen/forked-daapd#1092]
- ok on ubuntu focal+26.4 deb
- failed on ubunt focal and groovy+27.2 (git 7040382)
- `cast: Session error: The TLS connection was non-properly terminated.` found in 27.2 log (related to #275?)

[forked-daapd 26.4 deb log in debug mode.txt](https://github.com/ejurgensen/forked-daapd/files/5175280/forked-daapd.26.4.deb.log.in.debug.mode.txt)
[forked-daapd 27.2 git-7040382 log in debug mode.txt](https://github.com/ejurgensen/forked-daapd/files/5175281/forked-daapd.27.2.git-7040382.log.in.debug.mode.txt)

**Comment by ejurgensen** [comment]
I can't reproduce this with my Google Chromecast devices with Ubuntu Focal. It looks like the Mibox hangs up, but I don't know why. I don't have such a device to test with. 26.4 used an entirely different streaming method (not RTP based), so that is probably why it is working with the Mibox.

Do you have some Google Chromecast devices you could try with?

**Comment by ejurgensen** [comment]
Btw thanks for a very good bug report!

**Comment by keizie** [comment]
> I can't reproduce this with my Google Chromecast devices with Ubuntu Focal. It looks like the Mibox hangs up, but I don't know why. I don't have such a device to test with. 26.4 used an entirely different streaming method (not RTP based), so that is probably why it is working with the Mibox.
> 
> Do you have some Google Chromecast devices you could try with?

No other devices I have.
Hope further version will consider supporting 26.4-ish cast for compatibility with non-genuine chromecast built-in devices.

Ask me if I can test more with MIBOX4.
Thanks for great connectivity.

**Comment by keizie** [comment]
Chromecast with Google TV (2020) tested.

focal+git 3395773c9f68861ef0e492c0c93d4e0237fa6603 version also fail to play, just blink of black screen.

New Chromecast have `Chromecast built-in` app, as MIBOX4 does.
I suppose your chromecast device (might be 3, or ultra) may have different way of connection then `Chromecast built-in` app.

[forked-daapd 27.2 git-3395773 log in debug mode_chromecast2020.txt](https://github.com/ejurgensen/forked-daapd/files/5433067/forked-daapd.27.2.git-3395773.log.in.debug.mode_chromecast2020.txt)
(snip: trying to play via Remote.app)

**Comment by ejurgensen** [comment]
Thanks for the update. There is no error in the log, so no real clue there. I think I will have to get either a Xiaomi or one of those new Chromecasts to any further with this.

**Comment by ejurgensen** [comment]
I think I've found the cause of this now, and it is pretty weird. Apparently, these devices fail because forked-daapd does not announce a video stream during setup. It seems to be enough to just announce video, then everything works as it should, even though forked-daapd never actually sends any video packets.

Making a false video announcement seems wrong, so I think I will try to fix this by also sending a video stream with artwork.

**Comment by ejurgensen** [comment]
I've added a fix for this to master now, along with a bunch of other improvements to how forked-daapd streams to Chromecasts. I wasn't able to figure out how to send artwork as a video stream, hopefully I can find a solution for that later.
