### ISSUE TITLE
Update playlist when using Forked-daapd as internetradio with stations in playlist

### ISSUE THREAD

**Issue by Ulrichgau** [ejurgensen/forked-daapd#1097]
I use forked-daapd on a raspi as webradio. The different stations are arranged in a playlist. It would be cool if there were a scan in the background (every 60s?) of every entry in order to detect the title currently played in every station. So if I want to change the station I would know which song comes. I think in this case you also could detect commercials and maybe the suppress the annoying start with a commercial when changing the station has also an end.

**Comment by ejurgensen** [comment]
While I agree it would be a nice feature, I think it would be "rude" towards the radio stations. The track info is generally encoded in the mp3 stream, so forked-daapd would have to briefly start streaming all stations at regular intervals. And since the tracks are generally quite short, the interval would also have to be short. So I guess my answer is "no", but if someone can think a lightweight method I'm open to reconsideration.
