### ISSUE TITLE
[Radio Stream Config] Use external json metadata

### ISSUE THREAD

**Issue by mynameisdaniel32** [ejurgensen/forked-daapd#1153]
Stuck trying to get this to work, if it's at all possible, any help would be hugely appreciated!

My local radio station has an internet stream, available here:
http://live-radio01.mediahubaustralia.com/5TJW/mp3/

Unfortunately this only includes basic static metadata (so no album art or current track details).

They do however, have an API which lists the metadata I want in json format:
https://music.abcradio.net.au/api/v1/plays/triplej/now.json?tz=Australia/Adelaide

Is there any way I can merge these two in Forked Daapd?

I couldn't get overriding metadata to work following [this page](https://github.com/ejurgensen/forked-daapd/blob/master/README_RADIO_STREAMS.md), but seems it might be possible?

I also tried using #EXTM3U and #EXTIMG in an M3U file without any luck (#EXTIMG seems to be more of an IPTV thing anyway).

As an example, I'd like to select `now.release.artwork[0].url` as the album art, I can run a curl command every few seconds to do that, but couldn't work out the syntax (if it's even possible).

**Comment by ejurgensen** [comment]
There is currently no easy (or semi-easy) way to do this. Recently, there was a [similar request here](https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=49928&sid=9425317e5ad59321d630f4af60d3aee6&start=1575#p1777578), so that is always good as it increases my motivation to add the feature.

In the meantime, there are some more complicated routes to achieving what you are after, as you can also see from the link.

I'll keep the issue open and since the change itself shouldn't be that  complicated I think there is a reasonable chance it get be included in a forthcoming release.

**Comment by ejurgensen** [comment]
So I've now added a way to update the metadata of a track in the queue via the JSON api. The command for it [is this one](https://github.com/ejurgensen/forked-daapd/blob/master/README_JSON_API.md#updating-a-queue-item). All clients (incl. the web UI) should automatically update metadata when you make this update request. To set the artwork use the artwork_url parameter.

To make the call you need to have them queue item id of the track you want to update. If you just want to update the currently playing track you can get the item_id with [/api/player](https://github.com/ejurgensen/forked-daapd/blob/master/README_JSON_API.md#get-player-status).

Let me know if it works.

**Comment by ejurgensen** [comment]
I decided to make this a bit easier to use, so now I've added an alternative where the request can be made with "now_playing" instead of the item_id, saving a call to look up the item_id. So now something like this should do the trick:
`curl -X PUT "http://localhost:3689/api/queue/items/now_playing?title=Awesome%20title&artwork_url=http%3A%2F%2Fgyfgafguf.dk%2Fimages%2Fpige3.jpg"`
