### ISSUE TITLE
Can forked-daapd be configured to take audio-input from an USB audio-grabber? 

### ISSUE THREAD

**Issue by orakelet** [ejurgensen/forked-daapd#1155]
I have a RPi 2 with a USB audio grabber connected to a line-out from an old hifi. I have tried this combination with cpiped in between the USB-grabber and forked-daapd using a FIFO pipe. It works, but stutters and is not stable.

**Comment by ejurgensen** [comment]
Yes, the way to do this would be via a fifo. Without more information it is not possible to say what causes the stuttering. It could be that not enough audio is being written to the fifo, so that forked-daapd underruns. Then you should see a message in the log about source not providing enough data. To fix that you might need to check that the write sample rate is actually 44100.

Or it could be something else related to your USB input, which you could check by simply writing the audio to a file instead of a pipe, and then playing that and check if it is also unstable.

Since this is somewhat "before" forked-daapd I can't offer more specific help than this, so I will close the issue.
