### ISSUE TITLE
Soundbridge FLAC to ALAC

### ISSUE THREAD

**Issue by frankusb** [ejurgensen/forked-daapd#1182]
Is there a way to set the transcoding of FLAC to ALAC? Wired clients have no issue with 1.4Mbps WAV but the Soundbridge Radio only has 802.11b and I've been fighting it buffering for some time. I've setup a dedicated access point for 2 wireless Soundbridges but so far haven't quite gotten it physically close enough to be buffer free.

https://soundbridge.roku.com/support/dwnld_update_2_7.php states "Apple Lossless (ALAC) files may now be played natively, without transcoding on the server. Please note that some ALAC encoders don't write file information in the expected way, and these files may not play. Files encoded by iTunes should work fine."

**Comment by ejurgensen** [comment]
There is no way to do that right now, but I tried implementing just to see if it would work. I set ffmpeg to transcode to ALAC and to format as mpeg-4 (mp4/m4a). The latter turned out to be a problem. Apparently, [mp4 doesn't work with streamed encoding](https://stackoverflow.com/questions/25411836/ffmpeg-doesnt-work-with-mp4-and-stdout). Or maybe I just don't know how to get ffmpeg to do it.

I don't know if there are other formats for ALAC that the Soundbridge will understand.

Did you try converting some of your FLAC to MP4/ALAC and then setting "no_decode = { "alac" }" in the config file? Then I think the raw files should be served to your Soundbridge. Not exactly the solution you are after, but that way you can test if buffering is solved.

**Comment by frankusb** [comment]
I made the change to the config file, restarted forked-daapd, performed the below command and it played fine and showed the type as Kind: Apple Lossless audio file, Bit Rate: 870kbps.

ffmpeg -i song.flac -vn -acodec alac song.m4a

**Comment by frankusb** [comment]
I have other devices that do not support ALAC. Maybe ffmpegfs might be an option. Why can't everyone get along?

**Comment by ejurgensen** [comment]
I could add alac to [this list](https://github.com/ejurgensen/forked-daapd/blob/master/src/transcode.c#L56), then by default any Roku clients would get the source files, and your other devices might still work? Do you think that could work?

**Comment by frankusb** [comment]
Sorry, I meant devices not served by forked-daapd but copied from the same music files (portable music player, car).

So from the link regarding mp4 doesn't work with streamed encoding, I guess this implies ffmpegfs must do the entire file before responding?

**Comment by frankusb** [comment]
I don't see why you shouldn't allow alac to be served directly to Soundbridges though.

**Comment by ejurgensen** [comment]
Yes, seems the entire file needs to be encoded before the header can be written.

I've added alac. Other than that I can't think of anything to do, so I will close the issue.

**Comment by frankusb** [comment]
I appreciate you looking at it.

**Comment by frankusb** [comment]
I'm curious how Airplay clients can get served ALAC streams from FLAC source files but Soundbridge clients cannot.

**Comment by ejurgensen** [comment]
I don't exactly recall the issues with this, but re-reading the above indicates that we would need to serve the alac as m4a formated files, and that requires a different encoding/muxing paradigm. With Airplay, the container of the alac is RTP packets.

**Comment by frankusb** [comment]
Ah, that makes sense. Thank you.
