### ISSUE TITLE
itunes not able to see music library

### ISSUE THREAD

**Issue by gillecaluim** [ejurgensen/forked-daapd#120]
I'm not sure if there's a support forum but could use a little help
I've built and started forked-daapd on ArchLinux.
the log files shows that it successfully scanned music library....
[2015-03-12 15:29:30]       db: End of query results
[2015-03-12 15:29:30]     daap: Done with song list, 9809 songs
[2015-03-12 15:29:30]       db: DAAP request handled in 103 milliseconds
started itunes on a win7 laptop and it automatically sees the forked-daapd server but trying to browse the music library itunes says there's no music on the server????

**Comment by ejurgensen** [comment]
What version iTunes and forked-daapd? The problem sounds like this one: https://github.com/ejurgensen/forked-daapd/issues/100

That issue should be fixed with release 22.3 of forked-daapd.

**Comment by gillecaluim** [comment]
forked-daapd version 22.0
iTunes 12.1.1.4 64bit

**Comment by gillecaluim** [comment]
updating to 22.3 fixed issues...thanks

**Comment by gillecaluim** [comment]
was running forked-daapd 22.0....upgraded to 22.3 and it fixed issue.
Thanks

**Comment by gillecaluim** [comment]
thanks for keeping forked-daapd up to date.
Simple question.  I'm trying to stream from the forked-daapd server to an
ipad.  I'm amazed that Apple doesn't make this easy. What's the best
solution for this in your opinion?

**Comment by freultwah** [comment]
You mean turning the iPad into an AirPlay receiver? Something like this?

http://ios.wonderhowto.com/how-to/turn-any-ipad-iphone-ipod-touch-into-airplay-receiver-without-jailbreaking-0156869/

**Comment by gillecaluim** [comment]
Not sure if that does what I want. Is there a daap client ipad app that can
browse the forked-daapd db and stream the music from the forked-daapd
server to the ipad?

**Comment by ejurgensen** [comment]
If the AirPlay receiver freultwah mentioned works and runs nicely in the background (like some of the Android Airplay receivers do), then I think it would meet your need. You could then just browse with Remote. @freultwah have you tried the receiver? Is it any good?

I would also like to stream to my iPhone, and it puzzles me why Apple does not add the receiver ability themselves. I'm sure it would be easy for them to do. I guess there are some commercial reasons I can't see.

As you may have found, there is actually a DAAP client ("Simple DAAP client") in the app store, but it doesn't work with forked-daapd nor with iTunes. And it has not been updated since 2011.

So apart from the possible solution freultwah mentioned there is really nothing to do, to my knowledge. Maybe DLNA instead? Other people here might know better.

**Comment by gillecaluim** [comment]
Running archlinux and the libx264 was updated so now forked-daapd is
looking for the libx264.so.142 when the version I have is libx264.so.144.
How can I set it to use a symbolic link libx264.so which will always point
to the current version?

**Comment by ejurgensen** [comment]
Forked-daapd does not depend on that lib, but maybe ffmpeg does?
