### ISSUE TITLE
'Remote app' auto-pair option

### ISSUE THREAD

**Issue by HappyWafflez** [ejurgensen/forked-daapd#159]
If it was possible to support an option where "remote" apps on the same network auto pair with the library. This way control/access of the media server via the app can be throttled via a password rather then by manual pairing of new guest devices on the network.  

I assume there are limitations since the app generates a unique key to pair with a device. Thoughts?
__
Also, great work and excellent instructions. Everything works as advertised and I thoroughly enjoy using this version. Great for parties ! :) Thank-you

**Comment by ejurgensen** [comment]
Good to hear you like it!

I'm not sure I understand exactly what you mean by "access of the media server via the app can be throttled via a password" - isn't that what pairing is about?

I do, however, think I understand the concept of auto-pairing that you suggest. In the meaning that the user would select to add a library in the remote, get the PIN-code, but never use it, because the server would just pair immediately. Without actually testing it, I don't think that is possible with Apple Remote, because it most likely makes an actual check that the return value from the server matches the PIN. Other remotes may be lazy and skip that check, and then it could work. A problem would arise if the user actually didn't want to add the forked-daapd library, but some other library. Then this feature would become an obstruction. That problem can probably be mitigated by only auto-pairing with new Remotes.

**Comment by HappyWafflez** [comment]
Sorry for the confusion - In the forked-daapd.conf file there is an option under Library for password protection. I notice now that if a device is paired with a .remote file it bypasses the requirement of that password (at least on my instance of forked-daapd). 

I was confused because my laptop's iTunes library would show up on the remote apps of my iPhone and iPad automatically when launched (and i didn't remember pairing them). I know now that iTunes's Home Sharing pairs them by Apple ID which all my iDevices have in common with my laptop iTunes.

So if I understand correctly - auto-detection and population of a library in the remote app is not possible because the app explicitly requires a form of unique pairing
