### ISSUE TITLE
Any use of dmap.supportsautologout (msal) option?

### ISSUE THREAD

**Issue by roblan** [ejurgensen/forked-daapd#163]
Is there any way to force autologout after DAAP/DACP request?
Or how long session is valid?

**Comment by ejurgensen** [comment]
No, I don't think you can do that. What lies behind the question?

A session never expires. This comes from this commit https://github.com/ejurgensen/forked-daapd/commit/bd10978d5240bc22c03a6f3bd0492a6318b7d67d. Never expiring is not good practice in my opinion, so I will mark this as a bug. It won't be high priority to fix, because you are unlikely to end in a situation where this gives problems. Timeout changes are also a pain in the **** to test...

**Comment by roblan** [comment]
I'm trying to create a forked-daapd remote in browser and had a problem with logout on window/tab close, but I've resolved it.

**Comment by ejurgensen** [comment]
That sounds like a very interesting project. I see you don’t have it here on GitHub, but I hope that you will publish it some time.

**Comment by roblan** [comment]
I'm definitely going to :)
