### ISSUE TITLE
Forked-daapd in OpenWrt

### ISSUE THREAD

**Issue by MadsWesti** [ejurgensen/forked-daapd#184]
Will forked-daapd be added to the Chaos Calmer repo?

**Comment by ejurgensen** [comment]
It's already there, although the version is a bit old (22.3).

**Comment by MadsWesti** [comment]
Hmm weird.. Both opkg and the web interface doesn't recognise the package name. And I can't find the package and when i look through:
http://downloads.openwrt.org/chaos_calmer/15.05/ar71xx/generic/packages/

I'll have to investigate further :-) Thanks for the quick reply

**Comment by ejurgensen** [comment]
You are right, turns out I checked here before replying to you: https://downloads.openwrt.org/chaos_calmer/15.05-rc2/ar71xx/generic/packages/packages/

So it was in RC2, but got removed for the release, which is a pity. I didn't get any notification about this, so I don't know why. I will see if I can find the reason, and hopefully get it back in again.

**Comment by MadsWesti** [comment]
Ah then it also makes sense why i was able to install it in rc3 :) Thanks for the update

**Comment by ejurgensen** [comment]
I didn't find out what the reason was for this, but I have two suspects: libevent version conflicts and iconv dependency problems. Both of these should be dealt with in the most recent update to OpenWrt, so hopefully forked-daapd will now be included properly.
