### ISSUE TITLE
Internet audio stuttering - workaround

### ISSUE THREAD

**Issue by kalle2000** [ejurgensen/forked-daapd#218]
The internet radio audio stream starts stuttering after several hours (around 5 hours) of streaming for unknown reason. Is it possible to start a timer when a new internet radio stream is started and to restart the stream after, e.h. 4 hours?

**Comment by ejurgensen** [comment]
Yes, that might be the only realistic way of fixing this. Finding the actual problem would be really hard, unless some way of provoking it is identified.

**Comment by ejurgensen** [comment]
I decided to really pursue this bug and now I think I have been able to squash it.
 
As you can see, I have made a change that makes forked-daapd able to adjust its consumption of audio, so that it matches the rate it is delivered from the network stream. The issue was that forked-daapd requested audio slightly faster than it was delivered, and when the input buffer ran dry, you would hear stuttering.

When you have the opportunity to test it please let me know about the results.
