### ISSUE TITLE
enhancement: enhance logic for Artist display in Artists view (Apple Remote app)

### ISSUE THREAD

**Issue by kalle2000** [ejurgensen/forked-daapd#221]
When Apple Remote app is used, the view "Artists" can be used to show the library grouped by Artists. Currently the Artists within the Compilation folder and of "Various Artists" folder are excluded. Is it feasible to introduce a settings in the .conf file, to also show the Albumartists and Trackartists of Compilations and "Various Artists"? In case this setting is activated, in the Artists view only those entries shall be skipped, which are maintained as "Various Artists" indicator in the .conf file (compilation_artists).

**Comment by ejurgensen** [comment]
I have trouble understanding what the issue is, and what you are requesting. What do you mean by the “Various Artists” folder?

Perhaps you can achieve what you are after by disabling compilations and compilation_artist? If you do that the album view will contain each album_artist, and if there is no album_artist, then the track artist will be used.

**Comment by ejurgensen** [comment]
Closing, lack of feedback
