### ISSUE TITLE
Internet Radio Issue

### ISSUE THREAD

**Issue by xylle** [ejurgensen/forked-daapd#258]
Hello,
i follow this [page](https://github.com/ejurgensen/forked-daapd/blob/master/INSTALL) for install forked-daap on 2 Debian host amd64 and arm.

i have some issue with internet radio, i make this m3u file:
[frequence 3.m3u.txt](https://github.com/ejurgensen/forked-daapd/files/265067/frequence.3.m3u.txt)

i does'nt see this radio on internet radio of itunes ( Windows and Mac ), i see the apple list of radio.
In Apple remote on ios, i see and listen them.

Version of forekdaap :
Forked Media Server Version 24.1 taking off

Version of installed package:
[debian-deb.txt](https://github.com/ejurgensen/forked-daapd/files/265089/debian-deb.txt)

**Comment by xylle** [comment]
erratum:
in Apple remote i see it, but i can't listen them.

**Comment by ejurgensen** [comment]
iTunes issue: forked-daapd does not support serving internet radio streams to iTunes through DAAP, which is also why they are excluded in the iTunes views. It is also one these things where I don't really see a use case since there are plenty of other ways of playing internet radio on the desktop. So adding support for this is not high priority.

Remote issue: This should work. I tried making a m3u with your link, and it did work for me. So to find out why it is not working for you, I suggest you look for leads in the log file. (also: if you had this working you could use something like Remote + Shairport4w to play your radio streams on the desktop).

**Comment by xylle** [comment]
I don't known shairport4W, work fine.
I try to make multiroom audio system whith raspberryPi, forked-daap and shairport. i would like one system for all music. I want use it, with macos, Linux, Windows, Android, Windows Phone and ios
I can play internet radio with some over software, but i want one system.

I don't understand why, but now work with apple remote.

Thanks for your work and your help.
