### ISSUE TITLE
Enhancement: folder support for playlists

### ISSUE THREAD

**Issue by kalle2000** [ejurgensen/forked-daapd#272]
Today all playlists are collected and shown in a flat structure (except for e.g. Spotify).
Is it feasible to enable folder suctures for the ordinary playlists as well? This feature could be made optionally via .conf parameter.

**Comment by ejurgensen** [comment]
Yes, this should be feasible. I can think of two ways the user would do this:
1. Making a Parent playlist (a m3u) which contains the child playlists (also m3u's)
2. Putting the playlists in directories and then use a config option to tell forked-daapd to use the directories as parent playlist folders

The second requires a config option, and means the filesystem names and layout would matter, which is not so much in line with the current way forked-daapd works. But number 1 has some problems too. For instance, it allows a playlist to have multiple parent playlists, which wouldn't fit the current data model.

**Comment by chme** [comment]
I am working on implementing the mpd save command (saving the queue to a playlist file, issue #269, my branch: https://github.com/chme/forked-daapd/tree/storedplaylist2). It works but it is a bit clunky because the user needs to enter the whole virtual path

```
mpc save "file:/path/to/playlist/folder/playlistname"
```

It would be nice if it would be as simple as 

```
mpc save "playlistname"
```

This would be possible with option 2 with the small restriction that only one parent directory should be defined in the config. @ejurgensen have you given this feature further thoughts?

**Comment by sanjayradia** [comment]
I have been using the iTunes features of forked-daapd. They work great - the playlists show on iTunes and also on my very old  Roku music player just fine. Indeed it also works fine when i connect to my server from a remote site.  Thanks for this excellent work. 

Now let me comment on the topic of this thread on folder support for playlists.

 I don't manually create any additional playlists beyond those in iTunes (created on my desktop iTunes where I manage my music). I happen to use the folder feature of playlists in iTunes. When I connect via iTunes to my library on my forked-daapd server the folderized playlists are all flattened out and the folder in which the playlist were originally placed has all  the contents of the playlists merged in. I would have preferred to have the playlist appear folderized on iTunes just how they were on the original iTunes were I created them. As you work on this new folder support for playlist it would nice if you can retain the original iTunes folder structure if possible.

**Comment by ejurgensen** [comment]
@sanjayradia do I understand correctly that you import your playlists via the iTunes xml file? That might actually be a bit easier to support, since I expect it would just mean setting the parent folder as defined in the xml. The problem with multiple parent folders would not exist, I expect.

However, I can't say when I could get around to implementing this.

**Comment by sanjayradia** [comment]
Yes  I import via iTunes xml file. Thanks this will be a very useful feature.
Another useful feature would be to configure multiple libraries (e.g. my wife and I have different playlists via our own iTunes xml file. One can do this via multiple servers using different ports - haven't tried this yet and am not sure if iTunes depends on the port it simply uses rendezvous protocol to figure out the port.

**Comment by ejurgensen** [comment]
Closing this, I believe folders are now supported
