### ISSUE TITLE
Forked-Daapd cannot play music longer longer then 5-30 min Apple TV 4

### ISSUE THREAD

**Issue by ABrolund** [ejurgensen/forked-daapd#293]
Music played from Forked-Daapd stops after 5-30 min using Airplay on a Apple TV 4 as target. 
Airplay from the Apple TV is deselected in Forked-Daapd then, select it again it works for another 5- 10 min.
Using any Apple device as source for playback works fine.

Tested with Apple devices IOS9 and 10
Tested with Forked-daapd from Master at 1 Okt. 
Tested with Apple AppleOS 10.0

**Comment by Oggymator** [comment]
same problem here

**Comment by ejurgensen** [comment]
I was able to reproduce this is on the ATV4 I borrowed. The issue seems related to the new tvOS 10. I see Airfoil also has the problem. I didn't find out why iTunes does not get disconnects, but I did find a work-around, which I think should be ok for now. It is now in master, if you would like to try it.

**Comment by ABrolund** [comment]
I can confirm that it is fixed in Master from 9. Oct. (Tested around 3hrs on iOS9 and iOS10 devices as source)
I do not see that this issue was related to IPv6 as you mentioned in other tickets . Works also fine IPv6 enabled .
Thx a lot !
