### ISSUE TITLE
Spotify: Misleading information in log

### ISSUE THREAD

**Issue by ABrolund** [ejurgensen/forked-daapd#330]
Looking at the log forked-daapd complains about missing Spotify credentials. 
4 min later (no changes applied) it finds it and proceeds successfully 

[2017-01-04 16:59:17] [  LOG]     scan: Bulk library scan completed in 650 sec
[2017-01-04 16:59:18] [  LOG]  spotify: Could not login into Spotify: No credentials stored
[2017-01-04 17:03:45] [  LOG]  spotify: Spotify credentials file OK, logging in with username ....
[2017-01-04 17:03:46] [  LOG]  spotify: Login to Spotify succeeded, reloading playlists

**Comment by ejurgensen** [comment]
There is no so much I can do about this. Forked-daapd is just logging what is really happening: First libspotify says it has no stored credentials, then 4 min later it looks like inotify (the kernel) tells forked-daapd that a credentials file has been created or modified. I can't tell you why the latter happens if you haven't done anything yourself, but I can't see any way forked-daapd would trigger this event by itself.

Note that you should avoid keeping your credentials file in the library (or anywhere) in the first place. It is not required, and it is a risk to your Spotify password. What you should do is add it once (while forked-daapd is running, and after the bulk library scan) and then remove it again immediately. Forked-daapd only needs it for an instant to authenticate with libspotify.
