### ISSUE TITLE
where to find mixer parameter configuration?

### ISSUE THREAD

**Issue by dony71** [ejurgensen/forked-daapd#336]
I use I2S interface with alsa dmixer plugin
setting CARD="default" in forked-daapd.conf
However I get error cannot open mixer
amixer --card 1 shows 
Simple mixer control 'I2s Or Pcm Audio Mode Select format',0
so I set mixer="I2s Or Pcm Audio Mode Select format"
but still getting cannot open mixer
How to get correct mixer parameter value?
my .asoundrc
==============
pcm.!default {
        type plug
        slave.pcm "dmixer"
}

ctl.dmixer {
        type hw
        card 1
}

pcm.dmixer {
    type dmix
    ipc_key 1024
    ipc_perm 0666
    slave {
        pcm "hw:1,0"
        period_time 0
        period_size 1024
        buffer_size 4096
        rate 44100
        format S32_LE
        channels 2
    }
    bindings {
        0 0
        1 1
    }
}

**Comment by ejurgensen** [comment]
I don't know the exact answer to your question, but as a general recommendation I think you shouldn't change the default values ("default") in forked-daapd's config, but instead try to get card and mixer working on your system with "default". This will make it easier for you test, because you can use the aplay and amixer utilities. Aplay will use "default" as your card name, and amixer will use "default" as your mixer name. So if you can get those two working, forked-daapd should also work. An advantage of this approach is that it hopefully becomes easier to Google the answer. You don't need to Google for a forked-daapd specific solution, but on the more general question of setting the right default config for amixer on your platform.

Another time, please format your question properly (not in huge letters...), and also include the actual error messages you are getting. "cannot open mixer" is a broad category.
