### ISSUE TITLE
Title and Album Info Tag mixed up for Internet Radio Streams

### ISSUE THREAD

**Issue by kalle2000** [ejurgensen/forked-daapd#351]
Hi,

it looks like the metadata tags Title and Alum are mixed up. I tried a few radio stations and the Radio Station name appears in Title (I expected it in Album) whereas the Title is shown in Album.

Was this designed by purpose or can it be fixed?

thx
kalle

**Comment by ejurgensen** [comment]
Yes, this is on purpose. This "false" mapping was chosen because Remote primarily shows the title for playlist/radio items, and when you are looking for the radio station in these views, you are probably looking for its name, not the title of the last played track.

However, since then forked-daapd has been updated (thanks to @chme) with the ability to show one title in the Remote browser lists, and different one for the currently playing item. So it would be a minor change to support different mapping. Where exactly (which view) is it that you made your observation?

**Comment by kalle2000** [comment]
The area where the cover is normally shown is fine. It shows Title - Artist.
In the top "currently playing" area it seems to be mixed up.
