### ISSUE TITLE
spotify radio or your daily mix

### ISSUE THREAD

**Issue by snizzleorg** [ejurgensen/forked-daapd#369]
now that the Spotify web api is integrated and really great ... sorry I couldn't test it earlier. Just came back from 6 month parental leave. 

Would it be possible to also get a playlist for the daily mixes or for the recent Spotify radio stations?

**Comment by ejurgensen** [comment]
Neither libspotify nor web api expose Daily Mix, so that can't be offered, unfortunately.

I'm afraid the answer is the same for radio stations, but I'm not completely sure. This is a recently played service: https://developer.spotify.com/web-api/web-api-personalization-endpoints/get-recently-played/

@chme do you know what the possibilities are?

**Comment by snizzleorg** [comment]
Ok. I see...

**Comment by chme** [comment]
Besides the recently played endpoint there is the browse endpoint with new releases and featured playlist: https://developer.spotify.com/web-api/browse-endpoints/

But (as far as i know) no radio or daily mix support.
