### ISSUE TITLE
audio offset between BT and airplay

### ISSUE THREAD

**Issue by snizzleorg** [ejurgensen/forked-daapd#370]
Hi I just added a bluetooth speaker to my setup (4 airplay speakers so far.) Unfortunately there is a relatively big offset between the bluetooth and the airplay speakers. And changing it via the config (requiring a restart) is very cumbersome...
Is there a way to make this more comfortable ?

**Comment by ejurgensen** [comment]
Perhaps Pulseaudio has an option for dynamic buffer adjustment, but otherwise there isn't really an alternative. Adjusting the latency in forked-daapd while it is running probably would mean requirement for a web interface and of course also non-static config. Not something that is around the corner, I'm afraid.

**Comment by snizzleorg** [comment]
Yeah that is understandable. but what about putting out the latency of the airplay? as far as I know airplay adjusts the latency and therefore must determine the latency. 

My idea here is that the airplay speakers are later with a somewhat fixed amount of time because of the buffering - Right?

**Comment by ejurgensen** [comment]
Yes, you are correct, but the problem is getting the exact same latency on the Bluetooth device, because these timing controls are not available there (to my knowledge... I'm hardly an expert on Bluetooth audio). Forked-daapd does try to set a Pulseaudio latency of 2 seconds, because that matches the typical AirPlay latency, but your particular Bluetooth device might choose to buffer some more.

**Comment by snizzleorg** [comment]
hm. thanks for clarifying
