### ISSUE TITLE
Tagging Albums and Files on forked-daapd using iTunes

### ISSUE THREAD

**Issue by ubr** [ejurgensen/forked-daapd#393]
forked-daapd is awesome, thank you for your work! :heart_eyes: I just can't seem to get iTunes to edit MetaData for albums and files on my forked-daapd server.

For instance, when I click "Information" in iTunes for a music album on my forked-daapd server, I could in theory edit this album's Artist, Genre, Artwork etc in iTunes this way, but in practice, my changed tags are accepted but not being saved anywhere. Or, even worse, I can e.g. edit and save Album and Album Artist tags of three appearances of a CD in order to make them appear as one CD, and when I quit and re-open iTunes and go to my forked-daapd library, these changes are reverted as if I had never made them.  In addition, for individual music files instead of albums, the fields in the "Information" popup are grayed, and can't be changed.

On my server (Debian), my daapd user can write anywhere into forked-daapd's library and files system.  Why can't forked-daapd seem to update tags there?  Am I overlooking some basic functionality, or is there a technical barrier to tagging in forked-daapd from iTunes?

**Comment by ejurgensen** [comment]
There are some complications to this:
1. iTunes would have to send the updated metadata to forked-daapd, and I don't know if iTunes is able to do that
2. forked-daapd should then be able to update the source file's metadata (if writable), otherwise the changes will not be reflected in other applications, and you would risk loosing the changes if you happen to loose forked-daapd's own database

Even if the first is supported by iTunes, I don't think I will work on this capability, because I anticipate that the second would require a lot of work and add quite a bit of extra complexity.

**Comment by ubr** [comment]
thank you for your fast response. 

What tools do people then use to maintain the tags of a library that resides on a forked-daapd server?

And BTW, it's fascinating, just like with forked_daapd: When I open another _Mac's_ iTunes library in the LAN from iTunes on my Mac, I can seem to permanently edit the _remote_ album's tags in iTunes — but once I restart iTunes on my Mac, my changes on the remote album seem to be lost: exactly as with forked-daapd, you edit some tags and lose the edits once you quit iTunes.

It's amazing that iTunes offers to change tags in the first place if it'll lose the changes later: imagine someone spending hours tagging their library on a remote Mac (or forked-daapd server), and then all work is lost...
