### ISSUE TITLE
Inconsistency in toggling playing webstream via „mpc toggle“ or ympd

### ISSUE THREAD

**Issue by LordMyschkin** [ejurgensen/forked-daapd#428]
II noticed a small quirk: I recently used forked-daapd to play Radio Flemmes web stream; starting works as expected, stopping does also, but toggling from on to off gives an error in ympd and works in mpc but gives an error after.

**Comment by ejurgensen** [comment]
@chme will you look into this?

**Comment by chme** [comment]
Yes, i will look into it, but i won't have time before the weekend.

**Comment by chme** [comment]
@LordMyschkin i can't find the stream url for Radio Flemme. Can you post it or send it to me?

**Comment by chme** [comment]
@ejurgensen the issue here is, that forked-daapd does not support pausing radio streams and pipe input.

https://github.com/ejurgensen/forked-daapd/blob/617a0992d097621752d8cc24a8343c6c296174b1/src/player.c#L2303-L2327

In httpd_dacp.c the return value of `player_playback_pause` is ignored, while in mpd.c the return value is evaluated and the client receives an error message.

I see two solutions:

1. Ignore the return value of player_playback_pause in mpd.c (forked-daapd will still stop playback) 
2. Allow pausing radio streams (and pipe input)

I did a short test with one radio stream and removing the if-clause for DATA_KIND_HTTP and it seems to work. Do you see any downsides of this, or is it save to allow pausing streams/pipe input?

**Comment by ejurgensen** [comment]
I don't remember exactly what input_pause() does when it is a stream, but if it keeps the connection to the peer open and lets the streaming continue I think it is a problem. It wouldn't be nice to the peer, and it would consume needless bandwidth.

Remote only makes pauses, as far as remember, so a pause can be a long time.

**Comment by LordMyschkin** [comment]
thanks @chme for looking into this.
