### ISSUE TITLE
Two libraries on same server

### ISSUE THREAD

**Issue by luisspuerto** [ejurgensen/forked-daapd#494]
Hi! 

I really don't know if this gos here because it isn't a issue per se, but more a question. I was wondering if there is a forum somewhere to talk about something like this but I wasn't able to find one. 

Sorry if the question is a little bit silly or has a obvious answer. 

Right now I'm running forked-daapd under a cubox that acts as a NAS with Open Media Vault over armbian. I installed the plugin in OMV and also installed from the shell to be able to access to the web interface. Everything is running great –finally. 

I would like to know if it's possible to have two libraries under the same server. I mean, I now I just copied my iTunes folder one of the shares of the NAS and pointed forked-daapb to it. I would like to add to forked-daapd my wife's library. I'm thinking to create this short of structure. 

![screen shot 2018-02-22 at 10 33 03](https://user-images.githubusercontent.com/22882880/36527824-cacae130-17bb-11e8-923c-7512e2f2afa3.png)

Would that work? or am I going to create a mess? what is the expected behavior? are the two libraries going to mix and, since we have some music in common, daapb is going to show up two entries for that tracks? 

Thanks!

**Comment by ejurgensen** [comment]
Hi, your question is fine! I don't have a clear answer for you, though. In theory it might be possible, but who knows if that translates to practice. You will need to make sure that the two instances of the server don't fight over the same ressources. So that means:
- make a conf file for each instance
- configure different ports (daap, mpd and web)
- configure different locations of db_path, cache_path and logfile

Having the same uid and also sharing parts of the library between the two should be ok. Basically you want to avoid the two having access to write to the same ressource, but read should be ok.

The first thing to try before the above would be to change the value of "port" for your current single server, just to check that it still works with the clients you are using.

**Comment by luisspuerto** [comment]
Thanks for your reply! 

Perhaps I didn’t write my question correctly. I don’t want to have two instances of forked-daapb although it’s really cool to know that seems possible. I’m running forked-daapb in a really small server, a cubox board, so I want to use as less resources as possible. 

The question is more… what is going to happen if a throw two different libraries to the same folder where forked-daapb is pointed –music in this case. 

Thanks!

**Comment by ejurgensen** [comment]
I think I understand what your goal is, but one instance of forked-daapd cannot make two library shares. To do that you would need to run two instances.

However, I'm not sure I understand what you mean by "what is going to happen if a throw two different libraries to the same folder"? What would the throwing consist of?

**Comment by luisspuerto** [comment]
Ok

Right now I'm pointing forked-daapb to `/srv/dev-disk-by-label-OpL1TB/Media/Music/`. Under that folder there is this structure. 

![screen shot 2018-02-23 at 12 33 59](https://user-images.githubusercontent.com/22882880/36589982-d7ae7cb0-1895-11e8-9d6c-7ad6b17bfccc.png)

Right now there is nothing on `Olalla's iTunes`, but I want to know what is going to happen if I copy there another totally different iTunes library –my wife's one.

**Comment by ejurgensen** [comment]
It will just be indexed by forked-daapd like all the other folders below Music, and it will become available through the clients you use as one big collection. Forked-daapd doesn't know there is anything special about the different sub-directories.

**Comment by luisspuerto** [comment]
Thanks for your help! 

I'm coping the library. Let's see what happens.
