### ISSUE TITLE
Simple Control Remote Pairing

### ISSUE THREAD

**Issue by jompjomp** [ejurgensen/forked-daapd#513]
I have a edge case that I’d love help with, but I understand if it’s not worth anybody’s time. 

Simple Control (iOS home/AV control app) refuses to pair with daapd as a remote. 

I googled with Simple Control’s old name Roomie Remote and found this old post (there’s two of us!):
https://www.raspberrypi.org/forums/viewtopic.php?t=49928&start=225#p494025

I have no idea if that helps, I’m hoping so. Is there anything you need me to do?  If anybody has ideas, I’d love to hear them!

**Comment by ejurgensen** [comment]
I tried installing it, but turned out it is not free to try, so I couldn't really try it myself.

There is always the hope that the log could provide a clue. Can you set the log level to "debug" in the config, retry and then attach (not paste) the relevant part of forked-daapd's log?

**Comment by jompjomp** [comment]
I’ve attached the debug log. Hopefully you’ll see something in there that might make sense the situation.

Basically what happens is Simple Control sends the pairing, forked-daad sees it, but after I enter the four digits into the web interface or a .remote file, Simple Control just sits there and daapd stalls out.

Simple Control recently changed their subscription model so you sadly can’t have any free devices anymore. I’m willing to PayPal the $10 yearly Simple Control subscription with no expectation of results if it helps. I’m lost without my forked-daapd :)

[SimpleControlDAAPD.txt](https://github.com/ejurgensen/forked-daapd/files/1877246/SimpleControlDAAPD.txt)

**Comment by ejurgensen** [comment]
Actually I think there is work-around that you can try. I see that Simple Control actually tries to login first, but fails because it is not paired yet. What you can do is void forked-daapd's requirement for a pairing, which should make the login succeed. You do this by adding "10.0" (the prefix for 10.0.1.19) to "trusted_networks" in forked-daapd.conf and then restarting forked-daapd.

**Comment by jompjomp** [comment]
That work-around worked like a charm, thanks so much! 

Sadly, I’m using this docker and I’m also getting the crashing:

https://github.com/ejurgensen/forked-daapd/issues/502

**Comment by ejurgensen** [comment]
Great, I will then close this then - the workaround will have to do. I won't spend time on Simple Control pairing. Finding out why it is returning an empty response on the pairing request can be very time consuming, since it is basically reverse engineering.

#502 is difficult because it seems to require a special build of ffmpeg, or a special environment. You can probably get around it if you install your own ffmpeg. It is not too difficult to build ffmpeg, just download the source and then it is configure, make and make install.
