### ISSUE TITLE
ChromeCast stops streaming after 1 minute

### ISSUE THREAD

**Issue by jglooije** [ejurgensen/forked-daapd#514]
I have forked-daapd V26 installed on arch linux build from the AUR repository. Streaming to ALSA and shairport-express works perfectly, however if i stream to my chromecast music it will timeout after a minute. I also build the latest GIT with same result.

The log contains the following:

player: Input buffer has 355004 bytes
player: Input buffer has 355644 bytes
stream: Connection failed; stopping mp3 streaming to client
stream: No more clients, will stop streaming

Complete LOG below:
[forked-daapd.log](https://github.com/ejurgensen/forked-daapd/files/1876028/forked-daapd.log)

**Comment by ejurgensen** [comment]
I cannot reproduce this issue, unfortunately. I could only test using a regular ChromeCast, and I see you have a Chromecast Audio, maybe that makes a difference. I will try to get hold of one of those to see if it appears.

The log doesn't provide many clues - just that the Chromecast is disconnecting and then for some reason reconnecting right after.

Is the issue also present if you start playback and then just don't do anything else in Remote? From the above I see you also did some browsing of your library.

Another time please attach the log instead of pasting the complete thing.

**Comment by jglooije** [comment]
The issue is always there no matter what i do it will always stop after 1 minute. So for now is set the timeout   STREAMING_CONNECTION_TIMEOUT to 7200 in 'httpd_streaming.c' so i can listen for 2 hours un interrupted.

**Comment by ejurgensen** [comment]
Interesting that you could solve it like that. Do you know which version of libevent you are using? Would it be possible for you to check if the issue is also present if you run forked-daapd on another platform - e.g. Ubuntu, Debian or a Raspbian (if you have a RPi)

**Comment by jglooije** [comment]
I have libevent-2.1.8-1-x86_64.pkg.tar.xz currently installed. Testing on an other platform is not so easy i'll check this weekend.(i have RPi somewhere)

**Comment by jglooije** [comment]
This issue is solved in 26.5. Thanks for all the great work, keep it up!
