### ISSUE TITLE
change output-devices on forked-daapd

### ISSUE THREAD

**Issue by bendschs** [ejurgensen/forked-daapd#547]
i am using cantata on osx together with forked-daapd (on my raspberry pi). in genreal it works pretty well but i noticed, that i am not able to enable/disable the airplay-output devices through the menu of the web-interface (for local audio-output it is working properly). as i am not sure where the problem is a ticket is also opened here:  
https://github.com/ejurgensen/forked-daapd/issues/533

cheers,
bendsch

**Comment by ejurgensen** [comment]
@chme hope you can reply to this

**Comment by chme** [comment]
@bendschs Thanks for reporting it to the cantata developer. The fix for https://github.com/CDrummond/cantata/issues/1316 should solve the problem.
The airplay outputs have high output ids (> 255) in forked-daapd, that is why cantata did send the wrong output ids and forked-daapd did ignore the commands. It should be fixed with the next version of cantata (> v2.3.1)

**Comment by bendschs** [comment]
great, thx for the notification!
