### ISSUE TITLE
Independent speaker delay?

### ISSUE THREAD

**Issue by mb888** [ejurgensen/forked-daapd#560]
Hi, thank you for this absolutely great app! My issue is I'm using a combination of both shairport-sync and official AirPlay devices, the AirPlay devices are always slightly ahead of the shairport. Do you know of method to add a slight delay independently to each speaker. I know I could build a circuit with a TI audio delay chip but I'm looking for simple and elegant.

Thanks again for this great app!

**Comment by ejurgensen** [comment]
Can you test if this is also a problem if you use iTunes?

**Comment by mb888** [comment]
I just tried using itunes ( have never used iTunes previously as a source ). The test devices were two driven by shairport-sync and two official airplay devices. The two airplay devices were a Klipsch G17 Airplay speaker and a Denon AVR-X4300H. The shairport -sync devices played in sync with each other , there was a very slight delay but audible between the Klipsch and the shairport-sync's (Klipsch trailing) and a more noticeable delay between the Denon and the rest.

**Comment by ejurgensen** [comment]
What I’m really asking is if there is a difference between iTunes and forked-daapd, because there shouldn’t be. If the shairport speakers are delayed with both, then I think the issue is likely to be with the sound cards giving incorrect latency data to shairport. There is probably some shairport setting to correct for that, but that is a bit outside my realm.

**Comment by mb888** [comment]
I guess I'm looking for a solution that processes each speaker through independent fifos with adjustable delays  . I'll probably need to work it out myself when I have time.

Thank you!

**Comment by jshep321** [comment]
Hi, I have both apple devices (gen 1/2 apple TV) and old airport express alongside several raspberry pis running shairport-sync and a pioneer amp with built-in airplay.  My audio delay problems only exist on complex setups where I'm running audio through a device with DSP processing, which introduced delay.  

That being said, you can offset any shairport-sync devices in the config file (/etc/shairport-sync.conf):

`audio_backend_latency_offset_in_seconds = 0.0; // Set this offset to compensate for a fixed delay in the audio back end. E.g. if the output device delays by 100 ms, set this to -0.1.
`

I'd like to see this option on the server-side as well, but since I can tweak the shairport clients if needed, it's a low prio for me.

Try turning this knob and good luck!

**Comment by Ulrar** [comment]
I have a chromecast and an airplay (audiocast M5) device, they're almost synced but not quite.
It would be nice to be able to tweak this to get them in sync from the server, as the devices themselves don't have any such configs.

**Comment by maikvitesse** [comment]
I have one Google Home Mini (old gen) and three Nest Mini's (2nd gen).
The three nest mini's are perfectly in sync, but the google home mini is always out of sync.

Would be nice if i can configure a speaker delay for the Google Home Mini

**Comment by ejurgensen** [comment]
You can try with this in your config:

```
chromecast "YourHomeMiniName"
{
  offset_ms = xxxx
}

```

It isn't true sync, and isn't documented because I was hoping to find a better solution. The range you can set it to is from -1000 to 1000.

**Comment by maikvitesse** [comment]
> You can try with this in your config:
> 
> ```
> chromecast "YourHomeMiniName"
> {
>   offset_ms = xxxx
> }
> ```
> 
> It isn't true sync, and isn't documented because I was hoping to find a better solution. The range you can set it to is from -1000 to 1000.

Nice!! Thanks!
Works perfectly fine, i'm so happy now

**Comment by ejurgensen** [comment]
It only exists for Chromecast because Owntone doesn't have proper sync for that. For Airplay it shouldn't be needed and thus isn't an option.

**Comment by Cub3r4** [comment]
Hi there, I am rather new here with OwnTone, but already like that piece of code a lot.

I want to add here, that I also just tried to delay the airplay stream from a device, what as mentioned is not supported.
I just have one device connected (airplay) but encounter an delay between that one and http streams via browser (multiple http streams are pretty synchronized to each other), so i tried to offset the airplay device. Do you know a way to fix this? I did not find options in the config to shift airplay and http streams relative to each other...
Thanks :-)

**Comment by ejurgensen** [comment]
Hi @Cub3r4, there isn't a way to change those delays
