### ISSUE TITLE
feature request: different stream to different speakers at the same time

### ISSUE THREAD

**Issue by Albibox70** [ejurgensen/forked-daapd#662]
Hi,
maybe this request has already been made, but I've found nothing about it searching this kb:
If I want to have:
- only one library/db (and this is already possible)...
- managed by different Remotes (all connected to that library, and this is already possible)...
- but with the possibility to select and play at the same time different music on different speakers  (for example: Songs_1-2-3 on Speaker_A and Songs 2-5-6 on Speaker_B, and so on...)

Is this a feature possible in Forked-daap?
If not, any suggestion on how to obtain the same result (2 forked-daapd instances running, ecc)?

The most important thing would be using the same DB, in order to keep up to date only one music collection.

Best regards
Alberto

**Comment by ejurgensen** [comment]
The only way I can think of is a bit hackish and would require some work on your part. Two instances of forked-daapd can share the same library, but not the same db, so to get around that you would have to set up a cron job that cross-updates the databases. So you would have to make a script that does the sql to get updated values (based on the timestamps in the tables) from each db and then copies them over.

You would also have to make sure the instances have their own set of ports, so that means each their own conf file.

**Comment by ejurgensen** [comment]
BTW, if you go ahead with this then please add a page in the wiki (https://github.com/ejurgensen/forked-daapd/wiki), maybe someone else can then benefit from it as well
