### ISSUE TITLE
seems slow adding tracks to queue

### ISSUE THREAD

**Issue by whatdoineed2do** [ejurgensen/forked-daapd#701]
We have the ability to add many tracks at once from the web ui, in particular add all tracks for a genre to the playing queue - I had noticed that this was a little slow on my raspberry pi when adding my "Pop" genre which has about 540 tracks.  The `songs.db` file is sitting on a USB attached disk.

I took the db file to a dev machine and took a look to try to figure out what could be making the queue adds slow.

When adding tracks via the web ui, it does an map/join on the data before sending to the server but this (according to `console.time` / `console.timeEnd`) only took 7ms whilst it took about 1min 30 for the tracks to be added.  Taking all of the 540 uris and adding them via a single `curl` shows it takes 1min 18secs.

Adding smaller number of 17 tracks also seems a little slow, taking 3.2 secs:
```time curl -X POST 'http://localhost:3689/api/queue/items/add?uris=library:track:678,library:track:1575,library:track:725,library:track:1485,library:track:480,library:track:43,library:track:893,library:track:639,library:track:235,library:track:287,library:track:291,library:track:1590,library:track:816,library:track:1404,library:track:374,library:track:1572,library:track:1468'
{ "count": 17 }
real	0m3.283s
user	0m0.030s
sys	0m0.022s
```
This is the same when the play Q is empty or already has tracks.

Looking at the SQL required to lookup before the insert:
```
sqlite> SELECT f.* FROM files f WHERE f.disabled = 0 AND (f.id = 678)  ORDER BY f.album_sort, f.disc, f.track, f.title_sort ;
--EQP-- 0,0,0,SEARCH TABLE files AS f USING INTEGER PRIMARY KEY (rowid=?)
678|/media/music/Jackson 5/Unknown Album/00 - ABC.mp3|/file:/media/music/Jackson 5/Unknown Album/00 - ABC.mp3|00 - ABC.mp3|395|ABC|Jackson 5|Unknown album|Jackson 5|Pop||mp3||||||192|44100|178949|4296832|0|0|0|0|0|0|0|0|0|0|0|0|0|0|1|2|MPEG audio file|1548967939|1533912352|1480275710|0|0|0|0|mpeg|0|0|0|16||||0|0|8987887193162377064|8773143025816429577|ABC|Jackson 00005|Unknown album|Jackson 00005||8987887193162377064|
```

Does this timing seem right or is there something I can try to dig into?
thanks

**Comment by chme** [comment]
There is a bit of overhead for each uri that gets added to the queue (opening and closing a db transaction for the queue, and with each closing transaction the listeners for queue changes are notified). The overhead could be reduced to open one transaction and only closing it at the end after adding all uris to the queue.

But the easier solution for this performance problem is, to make use of the new query parameter `expression` for the queue/items/add endpoint. This query parameter takes a smart pl query expression and adds that in one db transaction to the queue (available since #651).

I am already working on making use of the new query parameters of the queue/items/add endpoint and will add sending a smart pl query instead of gathering all uris. My current work in progress branch for the changes: https://github.com/chme/forked-daapd/tree/web
