### ISSUE TITLE
[Request] Homescreen icon for Forked-Daapd

### ISSUE THREAD

**Issue by cdlenfert** [ejurgensen/forked-daapd#705]
I've added a shortcut (icon) to my iPhone's home screen for Forked-Daapd, but as you can see, it's not all that pretty. I'm wondering if it would be pretty simple to support a default icon for Forked-Daapd.

![img_4010](https://user-images.githubusercontent.com/17277745/53453351-138ddd80-39e1-11e9-9e8b-01e50536de01.jpg)

I'd be happy to take a stab at designing one if nothing is currently in the works. Maybe with reference to the Firefly icon.
![image](https://user-images.githubusercontent.com/17277745/53453471-6a93b280-39e1-11e9-8f17-65bf5b4d3f1e.png)

**Comment by chme** [comment]
I added a (rather generic) icon in different formats and sizes (i used an online generator), that should be used (https://raw.githubusercontent.com/ejurgensen/forked-daapd/master/htdocs/). It works on android (i do not own an iOS device, so cannot test there). 
The first problem to solve seems to be, that this icon is not used (or maybe it is used and the background color must be set to something different than black?).

<img src="https://raw.githubusercontent.com/ejurgensen/forked-daapd/master/htdocs/apple-touch-icon.png"/>

I think a custom icon for forked-daapd would be nice and as far as i know, no one is working on one.

**Comment by tsibley** [comment]
The problem is that `apple-touch-icon.png` has a transparent background, and the default background for app icons is black. On my local install, I made the icon below based on https://github.com/ejurgensen/forked-daapd/blob/master/htdocs/safari-pinned-tab.svg:

![apple-touch-icon](https://user-images.githubusercontent.com/79913/58218932-b773e600-7cbd-11e9-8ed7-f2d5b5674368.png)

I did scale down the play icon so it fit more pleasingly within the frame of the app icon once it gets rounded off. The image above is a PNG, but if someone wants the SVG I exported it from, let me know. Sorry I don't have time to make a proper PR, but maybe someone else can pick it up.

**Comment by tsibley** [comment]
(There is a slight gradient in the background, and the color is based on the accent color used elsewhere in the forked-daapd player.)

**Comment by cdlenfert** [comment]
@tsibley Did you have to Make forked-daapd and install again to get the icons to update? I tried replacing all icons in my local repo, cleared browser cache, but couldn't get the new icons to show in the web interface or as an iOS homepage icon. I had come up with something like this.

![mstile-150x150](https://user-images.githubusercontent.com/17277745/58283891-b6e35a00-7d66-11e9-849f-82c98ffeabb0.png)

**Comment by cdlenfert** [comment]
Update: I've built with the new image assets in the htdocs folder, however when I go to save the web interface to my iOS home screen, it's still the black triangle icon. I tried deleting history/data in safari settings. Not sure how I can get the new icon to work on the home screen. The new favicon is showing just fine in Chrome.

**Comment by tsibley** [comment]
I didn't bother rebuilding forked-daapd. Just dropped an updated `apple-touch-icon.png` into place and called it good for now. (Really short on time!) My device picked up the new icon immediately when I removed the web clip from the home screen and re-added it.

**Comment by cdlenfert** [comment]
Thanks for the info. I'm not having the same experience. I can confirm all icons on my system are updated and still when I "add to home screen" in Safari on iOS it's the black icon. Very strange.

**Comment by cdlenfert** [comment]
@chme I've submitted a PR with the new icons and updated version number in index.html

**Comment by cdlenfert** [comment]
Logo is a go!

**Comment by uvjustin** [comment]
@chme @cdlenfert I made a forked-daapd integration for Home Assistant and would like to use this icon to display along with the integration. Is there a way I can get the PNG in 256x256 and 512x512 resolutions?

**Comment by cdlenfert** [comment]
@uvjustin Here is the source file SVG (zipped). You should be able to make any size you want from it. 
[fd-logo.svg.zip](https://github.com/ejurgensen/forked-daapd/files/4623027/fd-logo.svg.zip)

I'm interested in your Home Assistant integration. What can you do with it? I'd very much like to control my FD server by voice with Alexa commands. Would that be possible via Home Assistant?

**Comment by uvjustin** [comment]
Thanks. The integration doesn't add any functionality by itself - it's kind of like a subset of forked-daapd's web player - but the key is integration with HA. The server and outputs show up as media player entities, and you can display and manipulate them using the HA front end. One neat feature is since it's a media player entity that supports the play_media service, you can forward text-to-speech announcements to all the outputs, kind of like a PA system for your house.
I'm not sure about Alexa integration in HA but I know voice commands are possible https://www.home-assistant.io/blog/2019/11/20/privacy-focused-voice-assistant/ .

**Comment by snizzleorg** [comment]
@uvjustin could you post a link to your integration?

**Comment by uvjustin** [comment]
@snizzleorg The integration just got pulled into the dev branch of HA core and should be in the next version (0.110)
