### ISSUE TITLE
Crackling with heavy base items

### ISSUE THREAD

**Issue by tropas2001** [ejurgensen/forked-daapd#706]
I appreciate this is a difficult issue to analyse, but I've got a situation where I'm playing a file with a heavy base (e.g. Sam Smith / Calvin Harris promises) which generates speaking crackling on the base beats. My setup is forked-daapd v24.2, hifiberry digi addon board, optical out into yamaha amp. 

The interesting thing is that when a play the same file through my iphone -> shairport-sync -> pipe -> forked-daapd - I don't get any crackling, even at a higher volume. 

I've tried converting the file for forked-daapd to play from M4A to mp3 and no difference. 

Any ideas?

**Comment by ejurgensen** [comment]
The only audio processing forked-daapd does is via ffmpeg libraries, which take care of decoding and resampling (if required). ffmpeg should be pretty good at that, so I would be surprised if that is the cause. You could try playing the file with "ffplay", just to check if the issue is also present in that case?

When you play via shairport-sync the decoding and resampling is done on the phone. Perhaps shairport-sync also does some audio processing. I don't remember if it adjusts volume when writing to a pipe. If it does, it might explain why the crackling is not present. You could try experimenting with shairport's volume settings, e.g. ignore_volume_control.

forked-daapd doesn't do any processing modifications of pcm samples received via the pipe. They get written straight to the sound system, which also takes care of volume control.

**Comment by tropas2001** [comment]
Thanks for your quick response. So I tried mplayer with both pulse and alsa outputs, no problems. I then reviewed my alsa config and I had been using a dmixer. I removed that and the crackling has gone.
