### ISSUE TITLE
HLS/m3u8 radio playback stops after about one minute

### ISSUE THREAD

**Issue by ste94pz** [ejurgensen/forked-daapd#745]
Hi, when I try to listen the radio in this m3u file

`#EXTM3U`
`#EXTINF:-1, - RDS 100% Grandi Successi`
`https://stream.rds.radio/audio/rds.stream_aac/playlist.m3u8`

the playback stops after about one minute as if the player reached the end of the file. If I want to continue the playback, I have to click one more time on the m3u in the library. I tried this m3u with VLC and it works without stopping, only with occasional breaks but It works. This is the output in the log when the playback stops:

`[2019-05-19 22:41:25] [  LOG]   player: Error reading source 'https://stream.rds.radio/audio/rds.stream_aac/playlist.m3u8' (id=10)`
`[2019-05-19 22:41:25] [  LOG]   player: Error reading from source`

Thank you for your great work on this awesome project.

**Comment by ejurgensen** [comment]
I’ve had a look at it, and this issue is both simple and difficult to fix.

The cause of it is that the ffmpeg library used by forked-daapd returns an error when reading the stream. It seems to happen when the tracks change, so there is something in the stream that ffmpeg doesn’t understand.

The simple fix would be for forked-daapd to just ignore the error, because it is just temporary. However, I’m not sure I will make that change, because that means forked-daapd will also ignore more serious, permanent errors (i.e. memory allocation failing). The fix is simple enough though, so if you build yourself you can build from this branch to try it: https://github.com/ejurgensen/forked-daapd/tree/ignore_ffmpeg_error

I have looked into ffplay and VLC source code to see what they do, since they are both able to play the stream. ffplay just ignores the error and keeps reading, which is interesting since it is not in accordance with ffmpeg’s own code examples. VLC seems to stop on error, like forked-daapd, so I guess the reason it works is that the underlying ffmpeg library does not produce an error. So perhaps if you upgrade the ffmpeg libraries it solves the issue?

**Comment by ste94pz** [comment]
I'm on ubuntu 18.04, the latest ffmpeg version is `7:3.4.6-0ubuntu0.18.04.1`. I tried to upgrade it to `7:4.1.3-0york1~18.04` from this ppa `jonathonf/ffmpeg-4`, but the playback doesn't start at all, both in normal and ignore_ffmpeg_error branches. In the log I have this:

`[2019-05-20 21:05:35] [  LOG]    xcode: Timeout while reading source (connection problem?)`
`[2019-05-20 21:05:35] [  LOG]    xcode: Timeout while reading source (connection problem?)`
`[2019-05-20 21:05:35] [  LOG]    xcode: Timeout while reading source (connection problem?)`
`[2019-05-20 21:05:35] [  LOG]    xcode: Timeout while reading source (connection problem?)`
`[2019-05-20 21:05:35] [  LOG]    xcode: Timeout while reading source (connection problem?)`
`[2019-05-20 21:05:35] [  LOG]    xcode: Cannot open 'https://stream.rds.radio/audio/rds.stream_aac/playlist.m3u8': Immediate exit requested`
`[2019-05-20 21:05:35] [  LOG]      web: Failed to start playback from position '0'`

I reverted to default ffmpeg with ignore_ffmpeg_error and the playback starts and it stops after some time like before, but now I have a lot of repeated entries like this:

`[2019-05-20 21:43:05] [  LOG]    xcode: Decoder error, avcodec_send_packet said 'End of file' (-541478725)`

**Comment by ejurgensen** [comment]
Yes, upgrading ffmpeg was bad advice. I have tested with trunk ffmpeg and like you I don't get any playback of your stream. Ignoring ffmpeg errors also doesn't help.

The ffmpeg and ffplay tools are able to read the stream, so I have to look more into what they are doing differently.

**Comment by ejurgensen** [comment]
I found what seems to be the cause of the problem when using newer ffmpeg version, it was an ffmpeg option (reconnect_at_eof). I have disabled it, and now playback works uninterrupted for me. Still doesn't work with ffmpeg 3.4, though. The fix is straight in master, I think it safe enough for that.

**Comment by ste94pz** [comment]
It works with ffmpeg 4.1.3, thank you very much! 👍
