### ISSUE TITLE
Web interface: Confusing feedback when queue is empty

### ISSUE THREAD

**Issue by beniamino38** [ejurgensen/forked-daapd#805]
If no songs are queued, and I hit the play button, I get a red error box with "Request failed (status: 500 Internal Server Error, url: http://house.willmore.eu:3689/api/player/play)". This is reasonable but a bit unfriendly -- it always takes me a while to realist that the error means that there are no songs queued up.

**Comment by whatdoineed2do** [comment]
This also happens on pause when its empty.

For me - and I suspect many others - the player should reseemble physical CD playe; with no CD loaded (ie no queue items) play and pause should just be a _ok, nothing to do_.

The fix for this is relatively simple in the `player.c`:
* `playback_start()`
```
      if (!queue_item)
      {
        count = 0;  // this
        db_count_get_count(&count);
        if (count == 0)
          ret = 0;
        return COMMAND_END;
      }
    }

  cmd_state = playback_start_item(queue_item, retval);
```

* `playback_pause()`
```
playback_pause(void *arg, int *retval)
{
  if (player_state == PLAY_STOPPED)
    {
      *retval = 0;  // this
      return COMMAND_END;
    }
```
