### ISSUE TITLE
Help Request: Utilizing the Json API

### ISSUE THREAD

**Issue by cdlenfert** [ejurgensen/forked-daapd#809]
I'm attempting to use a Pebble watch app called HTTP Push that allows Get/Put requests to be sent by the Pebble watch (via the iOS app). 
When I run the following command in my Mac's Terminal it works:
`curl -X PUT "http://forked-daapd.local:3689/api/outputs/75696725334744" --data "{\"selected\":true}"`

I'm trying to get the same command output from the HTTP Push app. Here is what the interface looks like:
![http-push](https://user-images.githubusercontent.com/17277745/64648966-3611a200-d3d9-11e9-997f-b2951a80287e.PNG)

However it sends a 400 response. I've tried setting up Get commands through the HTTP Push app to display a list of ouputs and that works totally fine. Just can't figure out the Put setup.

**Comment by whatdoineed2do** [comment]
On your PUT cmd in the app, do you need to escape the `“` as adding them (like what you show in the screenshot) is not valid json

**Comment by cdlenfert** [comment]
@whatdoineed2do that worked! Thanks for clarifying. Removed the backslashes and I'm in business. Now to write something much more complex that starts a specific playlists in the kitchen (only) with the proper volume. Wish me luck.

**Comment by cdlenfert** [comment]
@chme Another question that's come up is sometimes when enabling a set of speakers (or just a single speaker) via the `/api/outputs/set` endpoint, the volume will not be maintained to the previously set volume of the enabled speaker. 

My Garage speaker volume was set high (there's a lot of dead space in my volume slider in this shairport-sync speaker and sound doesn't start till ~50%), my Kitchen speaker was set low (~25%). When I enable the Kitchen only, the Garage is disabled (as I want), but then if I go back and enable the Garage only, the volume of the Garage goes to ~25%, instead of staying around 75%. Is this a bug, or expected behavior? I'm hoping the set volumes of each speaker will be maintained until I deliberately adjust them. Please let me know if you'd like me to move this into a new issue.

**Comment by cdlenfert** [comment]
Another idea, again I can start a new thread ... could there be a way to use a unique prefix and numbering sequence on IDs for Spotify playlists (sp1, sp2, sp3)? The use case is that I have a FD server at home and at work, and with this setup I could build 1 push request per Spotify playlist and hit it by the same ID at home or at work.

**Comment by chme** [comment]
> One thing I'm not sure has been discussed (but I'd find handy) is the ability to use a toggle parameter on individual outputs.

Can you open a new issue for that? It has not come up yet and should not be to hard to implement. 

> Is this a bug, or expected behavior? I'm hoping the set volumes of each speaker will be maintained until I deliberately adjust them. 

forked-daapd has a master volume and enabling a speaker while the player is not in the stopped state will not change this master volume. The reason is, that during playback enabling a speaker should not change the current master volume.
(One thing that could be discussed is, if this behavior is the expected one for the paused state or if the master volume should only be preserved if the player is actually playing)

> could there be a way to use a unique prefix and numbering sequence on IDs for Spotify playlists (sp1, sp2, sp3)?

Setting the ids is not possible. But for spotify playlists there is an alternative way to play these by their spotify uri (displayed as "path" in the details dialog in the web interface). This will not increase the play count etc. for the songs (forked-daapd treats these requests as playing non library tracks, this could be improved in the future, but has a very low priority for me).

```
http://music:3689/api/queue/items/add?uris=spotify:playlist:37i9dQZF1DX4fxf4OrMhXb&shuffle=false&clear=true&playback=start
```

**Comment by cdlenfert** [comment]
Thanks for the Spotify tip! Great solution, and play counts are very low priority for me too.

On the master volume what I'm observing is indeed that a higher volume of any individual speaker will increase the master volume.
![image](https://user-images.githubusercontent.com/17277745/65398444-74fa0d00-dd74-11e9-8bf9-b23d359db56f.png)

But when I disable that higher volume speaker (garage) the master volume doesn't change (at least in the web interface)
![image](https://user-images.githubusercontent.com/17277745/65398458-93600880-dd74-11e9-815b-e2b767783a2f.png)

And when I re-enable the garage speaker, the volume is set at the volume of the next highest speaker (office).
![image](https://user-images.githubusercontent.com/17277745/65398501-cd310f00-dd74-11e9-8df2-b503cce8b0c3.png)

Maybe the master volume just doesn't change visually, but does so behind the scenes? I'd definitely like there to be a way to retain the volume level of any individual speaker, but I understand if this would be much more complex than I'm making it out to be.

**Comment by chme** [comment]
That is a bug in the web interface, the master volume does change, but the web interface does not show the change. I opened a pr to fix this.

Keeping the volume from an output, instead of adjusting it to the current master volume, is doable. But would require a new config option of some sort ... and someone has to implement it :-)

**Comment by cdlenfert** [comment]
Thanks for confirming and making the PR for master volume updating in the web interface.
For now I'll see if I can't reconfigure my shairport-sync setup so I get sound on the lower range of my volume slider (instead of only hearing sound after 60%). That should suffice for myself.
