### ISSUE TITLE
Continuous overrun warnings on high resolution pipe

### ISSUE THREAD

**Issue by vasilisvg** [ejurgensen/forked-daapd#830]
I get input from a phono pre-amp via an Audio Injector Stereo card, and I try to pipe this to forked-daapd. This works fine if I keep the pipe at CD quality. 

```
arecord -f S16_LE -r 44100 -c 2 -t wav > /home/pi/music/pipe
```

It worked right away! Forked-daapd is incredible, it has to be said.

But when I try a higher resolution, like `S24_LE` things go wrong. I get continuous `"overrun!!! (at least 124.002 ms long)"` warnings. I wrote about this in [a bit more detail at the Audio Injector github repo](https://github.com/Audio-Injector/stereo-and-zero/issues/35).

Now I was wondering if maybe there’s a setting on the forked-daapd side of the pipe that might fix this. I looked in the configuration file but I couldn’t really find anything.

**Comment by whatdoineed2do** [comment]
For S_LE24 try setting in cfg and restarting. If you need to send S_LE16 you’ll need to comment this line out and restart again

```
library {
...
    pipe_bits_per_sample = 24
}
```

**Comment by vasilisvg** [comment]
Tried this but the pipe seems to break after a few seconds. There are still a few overrun warnings during those seconds.

**Comment by ejurgensen** [comment]
I have tested with 24 and 32 bps, and it also doesn't work for me. 24 bit will produce a crash, and 32 bit produces static. It looks like the crash is because alsa expects the audio buffer to be longer than it is, and that might be because it actually expects 4 bytes per sample. What is causing the static I don't yet know. I will look into it and get it fixed.

It did work fine for me with 16 bit and a sample rate of 96000. Can you confirm that? Remember set both values in the config.

**Comment by vasilisvg** [comment]
Could it have to do with [this Alsa driver issue](https://github.com/raspberrypi/linux/issues/494)?
(I'll test with 16 Bit 96000 when the family has left the living room 😄 )

**Comment by vasilisvg** [comment]
Ok, I can confirm, this works! 

In `/etc/forked-daapd.conf` I added:

```
pipe_sample_rate = 96000
pipe_bits_per_sample = 16
```
Then run the pipe like this:
```
arecord -c 2 -f S16_LE -r 96000 > /home/pi/music/pipe
```

**Comment by ejurgensen** [comment]
I've tested some more, and I think that if you make a build with the above commit https://github.com/ejurgensen/forked-daapd/commit/41f51d43ace7b975d2b386657017f6fe1c48146e then 32 bit should also work. After changing to 32 in the config you can then use:
`arecord -c 2 -f S32_LE -r 96000 -t raw`
It needs to be "raw" because the default "wav" will make arecord write some header data that forked-daapd currently doesn't understand (something for my todo list). You should in principle also use "raw" for 16 bit.

Your issue has also made me look more into 24 bit, and it looks like there are some special challenges there that I need to work with. I wasn't previously aware that 24 bit sometimes uses 4-byte samples, and that gives issues a few places in the current code.

**Comment by vasilisvg** [comment]
I can confirm that 32 bit works after making a build with the latest commit. Fantastic!
