### ISSUE TITLE
Could 88200 be a valid number for pipe_sample_rate?

### ISSUE THREAD

**Issue by vasilisvg** [ejurgensen/forked-daapd#838]
I managed to pipe music with 32bits 96 kHz from a record player via forked-daapd to another Raspberry Pi that runs Shairport Sync. 

Shairport Sync uses different values for its `output_rate` to alsa: 44100, 88200, 176400 or 352800. My Pi runs smoothly with an output rate of 88200.

This means that in this setup some resampling occurs.

I tried using a 32/88200 pipe with forked daapd, but I get this message:

```
forked-daapd[929]: [FATAL]   player: The configuration of pipe_sample_rate is invalid: 88200
```

Would it be possible to make 44100, 88200, 176400 and 352800 valid values as well for better compatibility with Shairport Sync?

**Comment by ejurgensen** [comment]
44100 is already supported, and 88200 should be fine, so I have added that. But I'm not sure it will do much for the quality, because Shairport Sync is probably receiving the audio at 44100? 

I don't know how the higher rates would perform, I'm thinking that perhaps the pipe buffers might be too small for that. I will hold that off for now, since it will in any case be rare to have a source that delivers in that resolution.
