### ISSUE TITLE
Short piped audio stuck in buffer

### ISSUE THREAD

**Issue by jshep321** [ejurgensen/forked-daapd#849]
Hi,
I'm playing around with integration of a voice assistant and like the idea of routing some responses across all my active speakers.  In my experimentation thus far, I made a pipe and am using ffmpeg to convert to pcm.  What I noticed is that if my audio clip is ~2 seconds or less, it doesn't play at all... until additional audio is sent to the pipe.   Same result for wav or mp3 (which are both converted to PCM).  It is simply stuck in a buffer somewhere.

If I'm already playing audio from another source and the "short" pipe audio comes in, it plays... which makes me doubt this is not inside of the pipe detection, but an output buffer?

Is is feasible to shorten this without breaking your pipe autostart detection design (or buffering)?

It also seems to cut off the end after it starts playing, but this might be a different issue.

my test command, fyi:
`ffmpeg -i shortfile.wav -c:a pcm_s16le -f s16le -ar 44100 -ac 2 pipe: > ~/music/jarvis`

Thanks!
PS if you want to test yourself, you can quickly crop an audio file with ffmpeg with -t = # of seconds:
`ffmpeg -i testfile.mp3 -ss 00:00:00 -codec copy -t 2 shortfile.mp3`

**Comment by ejurgensen** [comment]
Yes, the buffering is on the output side, so for Airplay the audio samples should all be sent to the device with little delay, but the device may not start playback until it has 2 seconds in its buffer (this might be device dependent). For local audio it will be held in a buffer by forked-daapd that won't be written to the device until there is 2 seconds. For Chromecast it's the same, but with a slightly shorter buffer.

So playing less than 2 seconds would require changes. I'm not sure what exactly they would be for pipe input, because it might be difficult for forked-daapd to know if there is more data coming (there is no clear EOF) and thus whether it should keep buffering, or whether playback should start.

Maybe the simplest solution for your case would be if you could get ffmpeg to append a bit of silence?

**Comment by jshep321** [comment]
Yep, I have done this and it seems to work.  However, other challenges have cropped up in my use case, such as how to save/resume the state before voice assistant audio arrives (spotify pipe or local playlist is interrupted and not restarted).  I think in order to do this properly, I redesign of forked-daapd would be needed to treat this (voice assistant piped) audio quite differently.  fun to play with, but not usable just yet. :)
