### ISSUE TITLE
m3u metadata not visible

### ISSUE THREAD

**Issue by kerihuelo** [ejurgensen/forked-daapd#891]
I have an issue with .m3u files. The following .m3u file (UTF-8) contains just one stream.

#EXTM3U
#EXTINF:-1,OE1 - OE1
http://mp3stream3.apasf.apa.at:8000

In the forked-dappd web frontend it is shown like this:

APAITtest
APAITtest
Unknown album

I guess the stream submits wrong metadata. Is there any way to force the name to be shown in the frontend? Are there any other solutions?

(This stream, by the way is the official stream of a popular radio station here in Austria. And I have similar issues with some other streams.)

**Comment by ejurgensen** [comment]
Yes, this is due to the metadata from the radio station. The right thing to do would be to write to them and ask them to set proper metadata. If you run "ffprobe http://mp3stream3.apasf.apa.at:8000" you can see that icy-name has that test name, and that there is no icy-description tag.

In the meanwhile, I think there might be a little trick you can employ to get better names: While you are not playing the station, unplug the internet connection and then run "touch [your m3u file]". This will cause forked-daapd to rescan the radio station, but since it can't reach it, I think it will fall back to using the names from the EXTINF tags (so "OE1"). Then just reconnect the internet. It should stay with the OE1, since forked-daapd will only rescan if you modify the file.

**Comment by snizzleorg** [comment]
Interesting. I would actually prefer if the meta data from the stream could be overwritten via the m3u as a lot of streaming services spam the metadata with useless stuff which is quite annoying...

**Comment by kerihuelo** [comment]
> Yes, this is due to the metadata from the radio station. The right thing to do would be to write to them and ask them to set proper metadata. If you run "ffprobe http://mp3stream3.apasf.apa.at:8000" you can see that icy-name has that test name, and that there is no icy-description tag.
> 
> In the meanwhile, I think there might be a little trick you can employ to get better names: While you are not playing the station, unplug the internet connection and then run "touch [your m3u file]". This will cause forked-daapd to rescan the radio station, but since it can't reach it, I think it will fall back to using the names from the EXTINF tags (so "OE1"). Then just reconnect the internet. It should stay with the OE1, since forked-daapd will only rescan if you modify the file.

Dear ejurgensen,

thank you for your reply. I tried your "trick" but it did not work. I will try again and wait a little bit longer before reconnecting the internet. Maybe it was cached somewhere? If someday it could be implemented that the #EXTINF information can override the stream information I would appreciate it. (All the other functionality of the forked-daapd "server" works fine. I am running on raspberry 4 and copied my 160 gb itunes mediathek today. After less than 15 minutes everything showed up in the frontend.)

And yes, I contacted the stream owner and informed them about the APAItest issue. Let's wait and see!

**Comment by ejurgensen** [comment]
Since I am working on playlists anyway I have included an option to let m3u metadata override, as you suggest. It is available in the playlist1 branch. You can set artist and title with EXTINF, and album with EXTALB. The branch also has a bunch of other changes that require more testing, so it will be not be merged right away. But if you could help with the testing it would be great.

**Comment by kerihuelo** [comment]
> But if you could help with the testing it would be great.

I will try to make an installation from the playlists1 branch. I am not a very experienced github user but I guess I will find instructions on howto do so online. I will let you know as soon as I got it up and running!

**Comment by ejurgensen** [comment]
The option to let m3u tags override is now merged into master. In case you tested from playlist1 I have to apologize for all the changes to the branch, maybe it was too unstable to test from.

**Comment by kerihuelo** [comment]
thanks! I tried to test it but was not able to get it running. I just installed the 27.1 via the "Quick version for Raspbian (Raspberry Pi)" link. It seems the feature it is not yet included. In any case many thanks for your effort!

**Comment by ejurgensen** [comment]
If you still want to test this you can install one of these versions with `dpkg -i [debfile]`. It will automatically be replaced by "apt upgrade" with newer versions, when I release them.

Raspbian Stretch:
http://www.gyfgafguf.dk/temp/forked-daapd_27.1.103~test1-2_armhf.deb

Raspbian Buster:
http://www.gyfgafguf.dk/temp/forked-daapd_27.1.103~test1-3_armhf.deb

**Comment by kerihuelo** [comment]
thank you for this info. I already reinstalled it by following the instructions for the "Quick version for Debian/Ubuntu users". it is running like a charm. stable and the m3u metadata is displayed as expected. all in all it is much more stable than my previous itunes on an old macbook. thanks again!
