### ISSUE TITLE
ignore filename quotes (linux/ext4)

### ISSUE THREAD

**Issue by jshep321** [ejurgensen/forked-daapd#892]
Hi,
After copying my entire local library from a fat32 USB drive to an ext4 USB drive, every file (and directory) with a space is now enclosed in single quotes.  As a result, all of my exported itunes playlists are empty, as the files aren't matched.  

Is it possible to ignore leading and ending quotes during playlist processing?
example directories:
Tool
'Toots & The Maytals'

Tool music is recognized just fine (assuming the files underneath have no quotes also), but Toots... is not.

If this isn't feasible then I suppose I can do some tricky bash script renames to remove the quotes to fix my problem--but others will likely have this also.

**Comment by ejurgensen** [comment]
That sounds pretty weird. Are you sure it is not just because `ls` is showing the filenames with quotes? You might try with `ls -N`. If you really have quotes I would get strongly suggest getting rid of them.

In any case, I would like to see the logging from the scanning of the playlist (with log level set to debug).

**Comment by ejurgensen** [comment]
Closing, no feedback
