### ISSUE TITLE
Forked-daapd lost ablity to get controled by my airplay speaker controls

### ISSUE THREAD

**Issue by LordMyschkin** [ejurgensen/forked-daapd#899]
Somewhere during last years updates, I lost the option to control the server by the controls on my Samsung E750 Audio Speaker.

**Comment by ejurgensen** [comment]
Can you see from the log (set to debug level) if forked-daapd is getting a request? It will say something like “dacp request”.

**Comment by LordMyschkin** [comment]
Well - now when testing, it works as it should. Strange  - I will examine that further.
is there a way i can restrict debug logging to interesting entries - log grew to 40 MBs in 5 mins:-)

**Comment by ejurgensen** [comment]
Yes, if you start it with:
sudo /usr/sbin/forked-daapd -d 4 - D main,dacp

If you do this you don’t need to edit the conf file.

**Comment by ejurgensen** [comment]
After a power outage my Sony also stopped being able to able to control forked-daapd. That was a clue, and I think I found the bug. I could see that the library ID used in the announcement was missing a leading zero. A library ID with a starting 0 would happen 1 out of 16 times the ID is calculated, and since it is not calculated that often, I was lucky to run into it. It also explains why it suddenly started working for you.

It should be fixed with the above commit.
