### ISSUE TITLE
Albums with tracks of different file format incorrectly split

### ISSUE THREAD

**Issue by lldsolitude** [ejurgensen/forked-daapd#914]
I have some albums that consist of both flac and mp3 tracks. In version 26.5, they show up in one single album in the web interface, but after updating to 27.1, they are split into two albums with the same name, with the flac tracks in one album and the mp3 tracks in the other. Please revert to the correct behavior in version 26.5. Thank you!

**Comment by ejurgensen** [comment]
I don't think it is the file format that is causing this, since forked-daapd does not use that to determine grouping. I suspect something else is the cause. I need more information to find out what that is. So it would be good if you could send me one of the flac tracks + one of the mp3 tracks. My email is espenjurgensen@gmail.com.

**Comment by ejurgensen** [comment]
I looked at your tracks, and the reason they show up as different albums is that the mp3 track has a "MusicBrainz Album Id" tag, while the flac has "MUSICBRAINZ_ALBUMID". Forked-daapd understands the former, but not the latter, so it wouldn't detect that they are actually the same album. I have fixed that now so that the latter is now also recognized. If you use my RPi distribution then you can get the fix just by running apt update and upgrade, because I have included the fix in the release I made just now. You probably need to rescan your library after updating.

The reason it worked with version 26.5 is that it understood neither of these tags, and instead just used the artist + album name.
