### ISSUE TITLE
Systemd restart limitation is obnoxious

### ISSUE THREAD

**Issue by mill1000** [ejurgensen/forked-daapd#968]
Get rid of this. Is your code so unstable you're really worried its going to crash and restart every 10 minutes?
https://github.com/ejurgensen/forked-daapd/blob/d3fb45196092abcc00e7d9764e9c9fd5db0c1024/forked-daapd.service.in#L25-L27

This restart limit makes it a PITA to tweak configurations because I have to reset the service every other time.

**Comment by ejurgensen** [comment]
Restart=on-failure is recommended for long-running services, but it can potentially lead to infinite restarting. That's the reason for the limits, but I agree they are unfortunate because they also apply to manual restarts. I think systemd should have made a RestartLimit option that only applies to automatic restarts.

If you know of a solution please let me know. Otherwise I think the issue can only be mitigated by increasing the burst value. I suppose I could set it to eg 10.

**Comment by mill1000** [comment]
Cool. That should ease a few frustrations. I agree it would be nice if systemd treated manual restarts as a separate counter.
