### ISSUE TITLE
disable spotify playlists download at startup 

### ISSUE THREAD

**Issue by beaudett** [ejurgensen/forked-daapd#988]
Hello,

I am so happy with forked-daapd that I decided to replace vlcd on the raspberrypizero-based (with wifi), battery-powered player of my son with forked-daapd. One motivation for this change is also the possibility to use spotify on it. The player is controlled with 5 buttons that are used to navigate through the m3u playlist, which contains a few spotify tracks. A push on these buttons triggers mpd commands. 

Given the limited resources of the computer, I would like to limit the startup
time as much as possible. To do so, I set 
```vacuum=false```  and  ```filescan_disable=true```.
With these settings, I noticed that the spotify playlists are nevertheless 
fetched at startup, and from the log, I see it takes about 1s per playlist. 
It is the main time consumer at statup.
Would it be possible to disable the reading of the spotify playlist at startup ? I would 
save about 1min startup time. In that case, would forked-daapd nevertheless be
able to play the spotify tracks listed in the m3u file ? Thanks !

**Comment by ejurgensen** [comment]
It's not possible currently, since the common use case requires that forked-daapd loads the current Spotify library. I think it is a great solution you have made, but it is also a rather special use case, so I won't prioritise supporting it.

Perhaps you could achieve what you are after if you combined librespot with forked-daapd, something like this:
1. Let the buttons trigger commands to librespot that start the tracks you want.
2. Let libresport write to a pipe in forked-daapd's library (forked-daapd will autoplay, so no direct user interaction with forked-daapd is required).
3. Run forked-daapd without Spotify.

That way forked-daapd should start very quickly, and I suppose librespot is also quicker to start.
